In [3]:
import pandas as pd
from datasets import load_dataset

#loading data
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [1]:
pip install --upgrade huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (0.33.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2025.6.15)

In [2]:
!pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.33.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [4]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [6]:
df.job_posted_date[0]

'2023-06-16 13:44:15'

In [8]:
dt=pd.to_datetime(df.job_posted_date)

In [9]:
type(dt)

pandas.core.series.Series

In [10]:
dt

0        2023-06-16 13:44:15
1        2023-01-14 13:18:07
2        2023-10-10 13:14:55
3        2023-07-04 13:01:41
4        2023-08-07 14:29:36
                 ...
785736   2023-03-13 06:16:16
785737   2023-03-12 06:18:18
785738   2023-03-12 06:32:36
785739   2023-03-12 06:32:15
785740   2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: datetime64[ns]

In [11]:
df["job_posted_date"]=pd.to_datetime(df.job_posted_date)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [13]:
df.job_posted_date.dt.month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

In [14]:
df['job_posted_month']=df.job_posted_date.dt.month

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

In [16]:
df.job_posted_month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_month, Length: 785741, dtype: int32

In [21]:
df["job_posted_day"]=df.job_posted_date.dt.day

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
 18  job_posted_day         785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(2), object(11)
memory usage: 92.2+ MB

In [23]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month,job_posted_day
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,6,16
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",1,14
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",10,10
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",7,4
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete...",3,13
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi...",3,12
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",3,12
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",3,12
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}",3,13

In [24]:
df.job_posted_day

0         16
1         14
2         10
3          4
4          7
          ..
785736    13
785737    12
785738    12
785739    12
785740    13
Name: job_posted_date, Length: 785741, dtype: int32

In [36]:
df.sort_values("job_posted_day",inplace=True) #inplace metodu otomotikmen false değerindedir bu metodu true olarak döndürürsek orijinal dataframe üzerinde işlem yapmamızı sağlar
#ve bu değer geri döndürülemez olduğu için orojinal datafram üzerinde daha sonra yapacağım değişiklikler üzerinde datafremimi yedeklemem lazım.

In [37]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month,job_posted_day
224074,Data Analyst,Data Analyst,"San José Province, San José, Costa Rica","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Costa Rica,2023-12-01 07:40:18,True,False,Costa Rica,None,NaN,NaN,Covalent Bonds,"['bigquery', 'gcp']","{'cloud': ['bigquery', 'gcp']}",12,1
402695,Machine Learning Engineer,Senior PowerBI Engineer - R01522880,"Bucharest, Romania",via Brillio - Talentify,Full-time,False,Romania,2023-03-01 18:30:59,True,False,Romania,None,NaN,NaN,Brillio,"['sql', 'sql server', 'azure', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'cloud'...",3,1
582669,Data Analyst,Data Administrator,"Geneva, Switzerland",via BeBee Schweiz,Full-time,False,Switzerland,2023-08-01 09:24:00,True,False,Switzerland,None,NaN,NaN,Michael Page,['gdpr'],{'libraries': ['gdpr']},8,1
357237,Senior Data Scientist,"Senior Data Scientist, International Growth at...","Plano, TX","via Plano, TX - Geebo",Full-time,False,Sudan,2023-08-01 00:19:06,False,False,Sudan,hour,NaN,24.0,reddit,"['sql', 'r', 'python']","{'programming': ['sql', 'r', 'python']}",8,1
629166,Senior Data Engineer,Senior Data Engineer Fully-remote,"London, UK",via FOX21News Jobs,Full-time,False,United Kingdom,2023-07-01 12:14:36,True,False,United Kingdom,None,NaN,NaN,Method Resourcing,"['python', 'sql', 'postgresql', 'snowflake', '...","{'cloud': ['snowflake', 'aws'], 'databases': [...",7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194838,Data Scientist,Lead Data Scientist,"Remote, OR",via Trabajo.org,Full-time,False,"California, United States",2023-08-31 15:06:29,False,True,United States,None,NaN,NaN,Synechron,"['python', 'aws']","{'cloud': ['aws'], 'programming': ['python']}",8,31
194849,Senior Data Analyst,Senior Data Analyst,"Birmingham, UK",via LinkedIn,Full-time,False,United Kingdom,2023-07-31 15:59:47,True,False,United Kingdom,None,NaN,NaN,Coltech Global,"['sql', 'sql server', 'excel', 'ssrs', 'power ...","{'analyst_tools': ['excel', 'ssrs', 'power bi'...",7,31
194890,Data Engineer,Data Engineer,"Beirut, Lebanon",via Emplois Trabajo.org,Full-time,False,Lebanon,2023-03-31 16:16:15,False,False,Lebanon,None,NaN,NaN,AlGooru,None,None,3,31
194414,Data Engineer,Data Engineer,Dubai - United Arab Emirates,via BeBee,Full-time,False,United Arab Emirates,2023-01-31 16:22:04,False,False,United Arab Emirates,None,NaN,NaN,Salt Search Ltd,"['sql', 'python', 'javascript', 'shell', 'orac...","{'cloud': ['oracle'], 'libraries': ['tensorflo...",1,31
194553,Senior Data Analyst,Senior Manager Data Analyst/Tableau developer,"Nutley, NJ",via LinkedIn,Full-time,False,"New York, United States",2023-05-31 15:00:01,False,False,United States,None,NaN,NaN,Pharma Search Partners,"['aws', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['aws']}",5,31

In [41]:
df.drop(labels="salary_hour_avg",axis=1) #drop metodu istediğim bi kısmı silmek için kullanılır axis 1 ise salary hour avg nin sütununu siler 0 ise satırını siler.
#kalıcı  yapmak istersem inplace metodunu kullanırım.

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month,job_posted_day
224074,Data Analyst,Data Analyst,"San José Province, San José, Costa Rica","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Costa Rica,2023-12-01 07:40:18,True,False,Costa Rica,None,NaN,Covalent Bonds,"['bigquery', 'gcp']","{'cloud': ['bigquery', 'gcp']}",12,1
402695,Machine Learning Engineer,Senior PowerBI Engineer - R01522880,"Bucharest, Romania",via Brillio - Talentify,Full-time,False,Romania,2023-03-01 18:30:59,True,False,Romania,None,NaN,Brillio,"['sql', 'sql server', 'azure', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'cloud'...",3,1
582669,Data Analyst,Data Administrator,"Geneva, Switzerland",via BeBee Schweiz,Full-time,False,Switzerland,2023-08-01 09:24:00,True,False,Switzerland,None,NaN,Michael Page,['gdpr'],{'libraries': ['gdpr']},8,1
357237,Senior Data Scientist,"Senior Data Scientist, International Growth at...","Plano, TX","via Plano, TX - Geebo",Full-time,False,Sudan,2023-08-01 00:19:06,False,False,Sudan,hour,NaN,reddit,"['sql', 'r', 'python']","{'programming': ['sql', 'r', 'python']}",8,1
629166,Senior Data Engineer,Senior Data Engineer Fully-remote,"London, UK",via FOX21News Jobs,Full-time,False,United Kingdom,2023-07-01 12:14:36,True,False,United Kingdom,None,NaN,Method Resourcing,"['python', 'sql', 'postgresql', 'snowflake', '...","{'cloud': ['snowflake', 'aws'], 'databases': [...",7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194838,Data Scientist,Lead Data Scientist,"Remote, OR",via Trabajo.org,Full-time,False,"California, United States",2023-08-31 15:06:29,False,True,United States,None,NaN,Synechron,"['python', 'aws']","{'cloud': ['aws'], 'programming': ['python']}",8,31
194849,Senior Data Analyst,Senior Data Analyst,"Birmingham, UK",via LinkedIn,Full-time,False,United Kingdom,2023-07-31 15:59:47,True,False,United Kingdom,None,NaN,Coltech Global,"['sql', 'sql server', 'excel', 'ssrs', 'power ...","{'analyst_tools': ['excel', 'ssrs', 'power bi'...",7,31
194890,Data Engineer,Data Engineer,"Beirut, Lebanon",via Emplois Trabajo.org,Full-time,False,Lebanon,2023-03-31 16:16:15,False,False,Lebanon,None,NaN,AlGooru,None,None,3,31
194414,Data Engineer,Data Engineer,Dubai - United Arab Emirates,via BeBee,Full-time,False,United Arab Emirates,2023-01-31 16:22:04,False,False,United Arab Emirates,None,NaN,Salt Search Ltd,"['sql', 'python', 'javascript', 'shell', 'orac...","{'cloud': ['oracle'], 'libraries': ['tensorflo...",1,31
194553,Senior Data Analyst,Senior Manager Data Analyst/Tableau developer,"Nutley, NJ",via LinkedIn,Full-time,False,"New York, United States",2023-05-31 15:00:01,False,False,United States,None,NaN,Pharma Search Partners,"['aws', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['aws']}",5,31

In [42]:
df.drop(labels="salary_year_avg",axis=1,inplace=True)

In [43]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month,job_posted_day
224074,Data Analyst,Data Analyst,"San José Province, San José, Costa Rica","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Costa Rica,2023-12-01 07:40:18,True,False,Costa Rica,None,NaN,Covalent Bonds,"['bigquery', 'gcp']","{'cloud': ['bigquery', 'gcp']}",12,1
402695,Machine Learning Engineer,Senior PowerBI Engineer - R01522880,"Bucharest, Romania",via Brillio - Talentify,Full-time,False,Romania,2023-03-01 18:30:59,True,False,Romania,None,NaN,Brillio,"['sql', 'sql server', 'azure', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'cloud'...",3,1
582669,Data Analyst,Data Administrator,"Geneva, Switzerland",via BeBee Schweiz,Full-time,False,Switzerland,2023-08-01 09:24:00,True,False,Switzerland,None,NaN,Michael Page,['gdpr'],{'libraries': ['gdpr']},8,1
357237,Senior Data Scientist,"Senior Data Scientist, International Growth at...","Plano, TX","via Plano, TX - Geebo",Full-time,False,Sudan,2023-08-01 00:19:06,False,False,Sudan,hour,24.0,reddit,"['sql', 'r', 'python']","{'programming': ['sql', 'r', 'python']}",8,1
629166,Senior Data Engineer,Senior Data Engineer Fully-remote,"London, UK",via FOX21News Jobs,Full-time,False,United Kingdom,2023-07-01 12:14:36,True,False,United Kingdom,None,NaN,Method Resourcing,"['python', 'sql', 'postgresql', 'snowflake', '...","{'cloud': ['snowflake', 'aws'], 'databases': [...",7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194838,Data Scientist,Lead Data Scientist,"Remote, OR",via Trabajo.org,Full-time,False,"California, United States",2023-08-31 15:06:29,False,True,United States,None,NaN,Synechron,"['python', 'aws']","{'cloud': ['aws'], 'programming': ['python']}",8,31
194849,Senior Data Analyst,Senior Data Analyst,"Birmingham, UK",via LinkedIn,Full-time,False,United Kingdom,2023-07-31 15:59:47,True,False,United Kingdom,None,NaN,Coltech Global,"['sql', 'sql server', 'excel', 'ssrs', 'power ...","{'analyst_tools': ['excel', 'ssrs', 'power bi'...",7,31
194890,Data Engineer,Data Engineer,"Beirut, Lebanon",via Emplois Trabajo.org,Full-time,False,Lebanon,2023-03-31 16:16:15,False,False,Lebanon,None,NaN,AlGooru,None,None,3,31
194414,Data Engineer,Data Engineer,Dubai - United Arab Emirates,via BeBee,Full-time,False,United Arab Emirates,2023-01-31 16:22:04,False,False,United Arab Emirates,None,NaN,Salt Search Ltd,"['sql', 'python', 'javascript', 'shell', 'orac...","{'cloud': ['oracle'], 'libraries': ['tensorflo...",1,31
194553,Senior Data Analyst,Senior Manager Data Analyst/Tableau developer,"Nutley, NJ",via LinkedIn,Full-time,False,"New York, United States",2023-05-31 15:00:01,False,False,United States,None,NaN,Pharma Search Partners,"['aws', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['aws']}",5,31

In [46]:
df.dropna(subset=["salary_hour_avg"]) #salary_hour_avg deki sütunlara bakar ve değerleri NaN olanları siler.

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month,job_posted_day
357237,Senior Data Scientist,"Senior Data Scientist, International Growth at...","Plano, TX","via Plano, TX - Geebo",Full-time,False,Sudan,2023-08-01 00:19:06,False,False,Sudan,hour,24.000000,reddit,"['sql', 'r', 'python']","{'programming': ['sql', 'r', 'python']}",8,1
356968,Data Analyst,"Data Analyst at Emory University in Atlanta, GA","Atlanta, GA",via Geebo,Full-time,False,Georgia,2023-10-01 00:00:01,False,False,United States,hour,24.000000,Emory University,"['sql', 'sql server', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'da...",10,1
109837,Data Analyst,"Data Analyst, Partner Operations (Ecosystem Pa...","San Francisco, CA",via RectDuty,Full-time,False,"California, United States",2023-01-01 00:01:11,True,False,United States,hour,20.000000,ByteDance,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",1,1
629402,Data Analyst,SAP Data Analyst,"Atlanta, GA",via LinkedIn,Contractor,False,Georgia,2023-09-01 13:05:29,False,True,United States,hour,51.500000,"Pyramid Consulting, Inc","['sap', 'excel', 'powerpoint', 'ms access', 't...","{'analyst_tools': ['sap', 'excel', 'powerpoint...",9,1
785492,Data Scientist,Data Scientist,"Arlington, VA",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:02,False,True,United States,hour,47.620003,Booz Allen Hamilton,"['python', 'r', 'pyspark']","{'libraries': ['pyspark'], 'programming': ['py...",11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203127,Data Analyst,Digital Data Analyst (Remote),"Charlotte, NC","via Charlotte, NC - Geebo",Full-time,False,Georgia,2023-08-31 23:30:12,False,False,United States,hour,24.000000,Sealed Air Corporation,"['sql', 'html', 'javascript', 'css', 'jquery',...","{'analyst_tools': ['power bi'], 'programming':...",8,31
201472,Data Analyst,Associate Data Analyst,Anywhere,via Indeed,Full-time,True,"Florida, United States",2023-05-31 15:01:51,False,False,United States,hour,30.000000,Brooksource,"['sql', 'sap', 'excel', 'flow']","{'analyst_tools': ['sap', 'excel'], 'other': [...",5,31
190942,Data Analyst,Excel Data Analyst,Anywhere,via ZipRecruiter,None,True,"New York, United States",2023-01-31 14:59:56,True,False,United States,hour,47.500000,The Phoenix Group,"['excel', 'word', 'spreadsheet']","{'analyst_tools': ['excel', 'word', 'spreadshe...",1,31
546030,Data Scientist,Data Scientist (NLP),"Charlotte, NC",via Dice,Contractor,False,Georgia,2023-05-31 19:54:58,False,False,United States,hour,55.000000,"AQUA Information Systems, Inc.",None,None,5,31
196997,Senior Data Engineer,Senior Data Engineer,Anywhere,via Upwork,Contractor,True,"New York, United States",2023-08-31 15:09:44,True,False,United States,hour,50.000000,Upwork,"['sql', 'python', 'aws', 'pyspark', 'linux', '...","{'cloud': ['aws'], 'libraries': ['pyspark'], '...",8,31

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 224074 to 194553
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_hour_avg        10662 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  job_posted_month       785741 non-null  int32
 17  job_posted_day         785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(2), object(11)
memory usage: 92.2+ MB

In [48]:
df.dropna(subset=["salary_hour_avg"],inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10662 entries, 357237 to 196997
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        10662 non-null  object
 1   job_title              10662 non-null  object
 2   job_location           10586 non-null  object
 3   job_via                10654 non-null  object
 4   job_schedule_type      10536 non-null  object
 5   job_work_from_home     10662 non-null  bool
 6   search_location        10662 non-null  object
 7   job_posted_date        10662 non-null  datetime64[ns]
 8   job_no_degree_mention  10662 non-null  bool
 9   job_health_insurance   10662 non-null  bool
 10  job_country            10662 non-null  object
 11  salary_rate            10662 non-null  object
 12  salary_hour_avg        10662 non-null  float64
 13  company_name           10662 non-null  object
 14  job_skills             9290 non-null   object
 15  job_type_skills        9290 non-null   object
 16  job_posted_month       10662 non-null  int32
 17  job_posted_day         10662 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(2), object(11)
memory usage: 1.3+ MB